# Sửa từ MONGODB_URI thành ${MONGODB_URI}

#spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.uri=mongodb://localhost:27017/beautyweb
#setx MONGODB_URI "mongodb+srv://user:pass@cluster.mongodb.net/beautyweb?retryWrites=true&w=majority&tls=true"
spring.data.mongodb.database=beautyweb

gemini.api.key = a401f704791898e7bb267a59e8d48bddc7d427fcb5331b0711f1bd1a4d968377 

#gemini.api.key2=${GEMINI_API_KEY}
gemini.api.url=https://openrouter.ai/api/v1/chat/completions
spring.main.allow-bean-definition-overriding=true

