# Sửa từ MONGODB_URI thành ${MONGODB_URI}

spring.data.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.database=beautyweb

gemini.api.key2=${GEMINI_API_KEY}
gemini.api.url=https://openrouter.ai/api/v1/chat/completions
spring.main.allow-bean-definition-overriding=true

